### ISSUE TITLE
README/Documentation suggestions

### ISSUE THREAD

**Issue by andrewferrier** [domharries/foldnav.nvim#2]
* Move the 'motivation' section higher up. It was kind of unclear to me originally why I would use this. Also, can you explain a bit more about why this is superior to `[z`, etc.?

* If you're interested, it's possible to generate a Vim 'help' file automatically from your README. See https://github.com/andrewferrier/debugprint.nvim/blob/main/.github/workflows/panvimdoc.yaml for an example.

**Comment by domharries** [comment]
Hi Andrew, thanks for the feedback!

* I think this is a great point. I've rewritten the start of the README to make this clearer.
* Thanks for the pointer to panvimdoc - now generated here: https://github.com/domharries/foldnav.nvim/blob/main/doc/foldnav.txt

I'll close this issue for now but please reopen if you don't think it's addressed.
